version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deploy-fe
    overwrite: yes

permissions:
  - object: /home/ec2-user/deploy-fe
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/change_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/reload_server.sh
      timeout: 300
