version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/deploy-fe

permissions:
  - object: /home/ec2-user/deploy-fe
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/remove_deploy_dir.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/reload_server.sh
      timeout: 300
      runas: ec2-user
